DROP TABLE IF EXISTS EXCHANGE_RATE;

-- 幣別對應表
CREATE TABLE EXCHANGE_RATE (
	EXCHANGE_ID INTEGER PRIMARY KEY auto_increment, -- ID
    	EXCHANGE_Date Date NOT NULL,
   	USD_TO_NTD DOUBLE NOT NULL	--美元兌換新台幣

);
